[2024-10-11T11:02:30.633+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: convert_yolov9_to_trt.convert_to_trt manual__2024-10-11T11:01:23.761496+00:00 [queued]>
[2024-10-11T11:02:30.642+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: convert_yolov9_to_trt.convert_to_trt manual__2024-10-11T11:01:23.761496+00:00 [queued]>
[2024-10-11T11:02:30.643+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-10-11T11:02:30.643+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2024-10-11T11:02:30.643+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-10-11T11:02:30.653+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): convert_to_trt> on 2024-10-11 11:01:23.761496+00:00
[2024-10-11T11:02:30.660+0000] {standard_task_runner.py:55} INFO - Started process 692 to run task
[2024-10-11T11:02:30.662+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'convert_yolov9_to_trt', 'convert_to_trt', 'manual__2024-10-11T11:01:23.761496+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/transform/main.py', '--cfg-path', '/tmp/tmp91t3pjey']
[2024-10-11T11:02:30.662+0000] {standard_task_runner.py:83} INFO - Job 176: Subtask convert_to_trt
[2024-10-11T11:02:30.710+0000] {task_command.py:388} INFO - Running <TaskInstance: convert_yolov9_to_trt.convert_to_trt manual__2024-10-11T11:01:23.761496+00:00 [running]> on host 4008dbb35820
[2024-10-11T11:02:30.761+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=convert_yolov9_to_trt
AIRFLOW_CTX_TASK_ID=convert_to_trt
AIRFLOW_CTX_EXECUTION_DATE=2024-10-11T11:01:23.761496+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-11T11:01:23.761496+00:00
[2024-10-11T11:02:30.763+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-10-11T11:02:30.763+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/dags/transform/yolov9/export.py ./model/model.pt ./model.engine']
[2024-10-11T11:02:30.778+0000] {subprocess.py:86} INFO - Output:
[2024-10-11T11:02:33.585+0000] {subprocess.py:93} INFO - usage: export.py [-h] [--data DATA] [--weights WEIGHTS [WEIGHTS ...]]
[2024-10-11T11:02:33.585+0000] {subprocess.py:93} INFO -                  [--imgsz IMGSZ [IMGSZ ...]] [--batch-size BATCH_SIZE]
[2024-10-11T11:02:33.585+0000] {subprocess.py:93} INFO -                  [--device DEVICE] [--half] [--inplace] [--keras] [--optimize]
[2024-10-11T11:02:33.585+0000] {subprocess.py:93} INFO -                  [--int8] [--dynamic] [--simplify] [--opset OPSET] [--verbose]
[2024-10-11T11:02:33.586+0000] {subprocess.py:93} INFO -                  [--workspace WORKSPACE] [--nms] [--agnostic-nms]
[2024-10-11T11:02:33.586+0000] {subprocess.py:93} INFO -                  [--topk-per-class TOPK_PER_CLASS] [--topk-all TOPK_ALL]
[2024-10-11T11:02:33.586+0000] {subprocess.py:93} INFO -                  [--iou-thres IOU_THRES] [--conf-thres CONF_THRES]
[2024-10-11T11:02:33.586+0000] {subprocess.py:93} INFO -                  [--include INCLUDE [INCLUDE ...]]
[2024-10-11T11:02:33.586+0000] {subprocess.py:93} INFO - export.py: error: unrecognized arguments: ./model/model.pt ./model.engine
[2024-10-11T11:02:33.951+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-10-11T11:02:33.960+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-10-11T11:02:33.964+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=convert_yolov9_to_trt, task_id=convert_to_trt, execution_date=20241011T110123, start_date=20241011T110230, end_date=20241011T110233
[2024-10-11T11:02:33.972+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 176 for task convert_to_trt (Bash command failed. The command returned a non-zero exit code 2.; 692)
[2024-10-11T11:02:34.000+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-10-11T11:02:34.016+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
